spring:
  data:
    mongodb:
      uri: mongodb+srv://nikhilnishad:LaE0msj8lpusnL77@cluster0.sv60irs.mongodb.net/?retryWrites=true&w=majority
      database: house_hunt
  task:
    scheduling:
      pool:
        size: 5
  mail:
    host: smtp.gmail.com
    username: nikhilatautopilot@gmail.com
    password: dgqjgbdfrqdcohya
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
   root: INFO
   
#springfox:
#  documentation:
#    swagger-ui:
#      base-url: app
